"""
Django settings for entryrecorder project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Env-controlled (see .env / .env.example) rather than hardcoded, so a real
# deployment can't accidentally ship with debug tracebacks/local variables
# exposed just because nobody remembered to flip this line by hand. Defaults
# to False (safe) if unset; local dev sets DEBUG=True in .env.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# Render injects this automatically for every web service — no manual env
# var needed for the default onrender.com hostname. A custom domain (if one
# is ever added) still needs to go in ALLOWED_HOSTS/CSRF_TRUSTED_ORIGINS above.
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'recorder',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'entryrecorder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'entryrecorder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASE_URL (set in .env locally, set in the Render dashboard/render.yaml
# for deployment) points at PostgreSQL. Unset locally, this falls back to the
# original SQLite file so `runserver` keeps working with no extra setup.
# DATABASE_SSL_REQUIRE defaults off since Render's internal DATABASE_URL
# (used when the web service and database are linked in the same Blueprint)
# doesn't need it — flip it on only if connecting to Postgres from outside
# Render's private network (e.g. an external connection string).

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        ssl_require=os.environ.get('DATABASE_SSL_REQUIRE', 'False') == 'True',
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# collectstatic's output (gitignored) — separate from STATICFILES_DIRS
# above, which is the source. WhiteNoise (added to MIDDLEWARE above) serves
# straight from here in production, so runserver never needs a separate
# static file server. Ignored by Django's runserver when DEBUG=True, which
# serves STATICFILES_DIRS directly instead.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Manifest storage requires collectstatic to have already run (it
        # looks up hashed filenames from a manifest file) — fine in
        # production where the build step always runs collectstatic first,
        # but breaks {% static %} in local dev/tests, which never do. Only
        # switched on when DEBUG is off.
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Auth
# Single-user app: the Django superuser doubles as the app login and the
# /admin login — no separate credential store.

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'


# Home page "select all" + bulk delete/PDF-download post one POST field per
# selected entry id. Django's default DATA_UPLOAD_MAX_NUMBER_FIELDS (1000)
# is exceeded once there are that many entries, raising TooManyFieldsSent
# before the view even runs. Single-user app with no untrusted form
# submitters, so raising this is safe rather than a DoS concern.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000


# Email
# Used by Account Settings' "Change Email" OTP flow (recorder/views.py).
# Real credentials go in .env (gitignored) — see .env.example. Until
# EMAIL_HOST_PASSWORD is filled in, sending will fail; the view catches that
# and reports a clean error instead of a 500.

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# Django's SMTP backend has no timeout by default, so a stalled connection
# to EMAIL_HOST blocks indefinitely. On Render that runs past gunicorn's
# default 30s worker timeout, which SIGKILLs the worker mid-request --
# Render's edge then returns its own 502 HTML page instead of the clean
# JSON error the view's own try/except (recorder/views.py) is meant to
# return. Keeping this well under 30s means a stuck connection fails fast
# and actually reaches that except block.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 10))


# Production-only transport/cookie hardening
# Tied to `not DEBUG` (now env-controlled above) rather than always-on, so
# local dev over plain HTTP (DEBUG=True) isn't broken by cookies/redirects
# that require HTTPS. Deployment target is Render: its edge proxy terminates
# TLS and sets X-Forwarded-Proto on every request, so SECURE_PROXY_SSL_HEADER
# below is safe to trust — this would NOT be safe on a host where an
# untrusted party could set that header directly.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None
SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# CSRF needs the scheme in each trusted origin (Django 4+), unlike
# ALLOWED_HOSTS. RENDER_EXTERNAL_HOSTNAME is Render's own env var (see
# ALLOWED_HOSTS above) — always HTTPS on Render, so hardcoding the scheme
# here is safe. A custom domain added later needs to go in the
# CSRF_TRUSTED_ORIGINS env var (comma-separated, full origin incl. scheme).
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')
