# Generated by Django 5.2.16 on 2026-07-31 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('vehicle_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid vehicle number, e.g. MH12AB1234.', regex='^(?i:[A-Z]{2}[0-9]{1,2}[A-Z]{1,3}[0-9]{4})$')])),
                ('rolls', models.PositiveIntegerField()),
                ('workers', models.PositiveIntegerField()),
                ('net_kg', models.PositiveIntegerField()),
                ('remark', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
