# Generated by Django 5.2.16 on 2026-07-31 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0004_entry_batches_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
