# Generated by Django 5.2.16 on 2026-08-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0006_entry_new_table_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='loading_roll',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Loading/Roll'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='net_kg_loading_roll',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Net Kg (Loading/Roll)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='net_kg_weight_roll',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Net Kg (Weight/Roll)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='weight_roll',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight/Roll'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='workers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
