# Generated by Django 5.2.16 on 2026-08-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0007_alter_entry_loading_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
