# Generated by Django 5.2.16 on 2026-08-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0009_alter_entry_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
