# Generated by Django 5.2.16 on 2026-08-08 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0010_alter_entry_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='loading_roll',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Loading/Roll'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='net_kg_loading_roll',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Net Kg (Loading/Roll)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='net_kg_weight_roll',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Net Kg (Weight/Roll)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='weight_roll',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight/Roll'),
        ),
    ]
